services:
  backend:
    build:
      context: ./backend
    container_name: how-pulse-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: how-pulse-frontend
    ports:
      - "5500:80"
    depends_on:
      - backend
    restart: unless-stopped
